### ISSUE TITLE
Need LICENSE

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs-archive#1]

**Comment by josh-heyer** [comment]
Since this is a public repo, we should have a content license that reflects what rights we reserve for the use of the PDFs that will be hosted here. @drothery-edb can you follow up on this?

**Comment by drothery-edb** [comment]
@josh-heyer can you point me to the license file used for Docs 1.0?

**Comment by drothery-edb** [comment]
Discussed with Kelly and we can use the standard EBD copyright license file. For example, the file that is in the mysql_fdw repo. We were wondering why that standard EBD license file was not used for Docs 2.0.

**Comment by josh-heyer** [comment]
Fixed by #2
